imports:
 - {resource: config.yml}

#==Framework
framework:
 test: ~
 handle_all_throwables: true
 php_errors:
   log: true
 profiler:
  collect: false

#==Web Profiles
web_profiler:
 intercept_redirects: false
 toolbar: false
